### ISSUE TITLE
List with all_pages=True doesn't seem to work

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#130]
Create enough organizations to cause pagination. Next, list all pages

    tower-cli organization list --all-pages

I obtain the following traceback:

```
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/cli2/bin/tower-cli", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-tower-cli==2.3.1', 'tower-cli')
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1650, in run_script
    exec(code, namespace, namespace)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/EGG-INFO/scripts/tower-cli", line 80, in <module>
    cli()
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/utils/decorators.py", line 49, in answer
    return method(*inner_a, **inner_kw)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 286, in func
    result = method(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 700, in list
    cursor = self.list(**dict(kwargs, page=cursor['next']))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 693, in list
    response[key] = int(match.groupdict()['num'])
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

It seems that in `base.py` the code is looking for a `page=` marker within a regular expression, but it's just not there. The response contains the following:

```yaml
{
'count': 56, 
'next': 2, 
'previous': None,
# ...more data...
}
```

Maybe the `next` field used to contain some more complicated string, but it doesn't any more.

**Comment by AlanCoding** [comment]
Never mind. This was due to other things unique to my environment. It shouldn't affect any other users out there. Closing it out.
