### ISSUE TITLE
Error when syncing a group with --monitor

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#153]
Run the command `tower-cli group sync "group_name" --monitor`, where group_name is the name of some group with a cloud source. Or, use the primary key in place of the group name.

When the job finishes and it tries to print the output, the traceback is produced:

```
Current status: successful
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/cli2/bin/tower-cli", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-tower-cli==2.3.1', 'tower-cli')
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1650, in run_script
    exec(code, namespace, namespace)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/EGG-INFO/scripts/tower-cli", line 80, in <module>
    cli()
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/utils/decorators.py", line 49, in answer
    return method(*inner_a, **inner_kw)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 298, in func
    output = format(result)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 362, in _format_human
    *[len(six.text_type(i[col])) for i in raw_rows]
KeyError: 'inventory'
```

**Comment by jangsutsr** [comment]
Issue neutralized in PR 153. Closing the issue...
