### ISSUE TITLE
Bad input in associate gives traceback

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#159]
```
tower-cli organization associate --user test_user
```

I expect a user error stating what went wrong. But I get:

```
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/cli2/bin/tower-cli", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-tower-cli==2.3.1', 'tower-cli')
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1650, in run_script
    exec(code, namespace, namespace)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/EGG-INFO/scripts/tower-cli", line 80, in <module>
    cli()
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/utils/decorators.py", line 49, in answer
    return method(*inner_a, **inner_kw)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 287, in func
    result = method(*args, **kwargs)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/resources/organization.py", line 34, in associate
    return self._assoc('users', organization, user)
  File "/Users/alancoding/.virtualenvs/cli2/lib/python2.7/site-packages/ansible_tower_cli-2.3.1-py2.7.egg/tower_cli/models/base.py", line 731, in _assoc
    url = self.endpoint + '%d/%s/' % (me, url_fragment)
TypeError: %d format: a number is required, not NoneType
```

**Comment by jangsutsr** [comment]
Strange. I tested it and could not replicate the issue:
```
(tower_cli_devel) sitan-OSX:tower-cli sitan$ tower-cli organization associate --user test_user
Error: Could not get user. The requested object could not be found.
```

**Comment by AlanCoding** [comment]
Give it a valid user and I bet you'll see it too.
