### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by Fale** [ansible/tower-cli#205]
Trying to run tests on Fedora 26 with Python 3.5, I receive the following errors.
I'm not sure if it's a missing piece in my side or not.
On the same environment, running the tests against Python 2.7 is a success.

```
======================================================================
ERROR: Establish that if connection fails and protocol not given,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_api.py", line 199, in test_failed_suggestion_protocol
    secho.assert_called()
  File "/usr/lib64/python3.5/unittest/mock.py", line 583, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called

======================================================================
FAIL: Establish that if `tower-cli config` is sent an invalid key,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 193, in test_error_invalid_key
    self.assertEqual(result.exit_code, 1)
AssertionError: -1 != 1

======================================================================
FAIL: Establish that if no global config file exists, that tower-cli
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 214, in test_error_no_global_config_file
    isdir.assert_called_once_with('/etc/tower/')
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'isdir' to be called once. Called 0 times.

======================================================================
FAIL: Establish that if `tower-cli config` is called with both a value
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 202, in test_error_value_and_unset
    self.assertEqual(result.exit_code, 2)
AssertionError: -1 != 2

======================================================================
FAIL: Establish that if we are given a key and no value, that the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 59, in test_key_and_no_value
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: Establish that if `tower-cli config` is called with no arguments,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 46, in test_no_arguments
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: Warn user if configuration file permissions can not be set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 101, in test_permissions_warning
    warn.assert_called_once_with(mock.ANY, UserWarning)
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'warn' to be called once. Called 0 times.

======================================================================
FAIL: Establish that calling `tower-cli config --unset` works in the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 180, in test_unset
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: Establish that if we attempt to write a valid setting, that
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 126, in test_write_global_setting
    isdir.assert_called_once_with('/etc/tower/')
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'isdir' to be called once. Called 0 times.

======================================================================
FAIL: Establish that if we attempt to write a valid setting locally, that
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 154, in test_write_local_setting
    chmod.assert_called_once_with(filename, int('0600', 8))
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'chmod' to be called once. Called 0 times.

======================================================================
FAIL: Establish that if we attempt to write a valid setting, that
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 75, in test_write_setting
    chmod.assert_called_once_with(filename, int('0600', 8))
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'chmod' to be called once. Called 0 times.

======================================================================
FAIL: Establish that if we attempt to write a valid setting, that
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_config.py", line 264, in test_write_global_setting_deprecated
    DeprecationWarning)
  File "/usr/lib64/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'warn' to be called once. Called 0 times.

======================================================================
FAIL: Establish that the version command gives a nice error in cases
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_version.py", line 58, in test_cannot_connect
    self.assertEqual(result.exit_code, 1)
AssertionError: -1 != 1

======================================================================
FAIL: Establish that the version command returns the output we
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_commands_version.py", line 45, in test_version_command
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: Establish that no_args_is_help causes the help to be printed,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/tower-cli-3.0.0/tests/test_utils_command.py", line 42, in test_dash_dash_help
    self.assertEqual(self.runner.invoke(foo, ['bar']).output, 'bar\n')
AssertionError: '' != 'bar\n'
+ bar
```

Thanks a lot :)

**Comment by AlanCoding** [comment]
I tried running tests on Ubuntu 14.04 with python 3.5, and it looks like I just replicate your first error, that `assert_called` error.

The rest of them are probably not a python3.5 thing, and related to something with the operating system and the config file management system, or maybe the CLI mocking library.

Ideally, I would like to get python3.5 in the travis automated tests. They say they support it, but the image needs to be updated somehow and I'm not quite sure how to get that working right now.

So it looks like we have at least a python 3.5 bug revealed in the tests, and probably some OS-specific config file problems.

**Comment by Fale** [comment]
As far as I see, it's enough to add a line in https://github.com/ansible/tower-cli/blob/master/tox.ini#L2 to add py3.5 coverage (travis-ci should automatically understand and process)

**Comment by Fale** [comment]
I've also opened a similar bug against python-click on Fedora Bug tracker at https://bugzilla.redhat.com/show_bug.cgi?id=1379773

**Comment by jangsutsr** [comment]
Observation: One upstream testing mocker `click.testing.CliRunner` seems to be the root of all above test failures. There might be compatibility issues in there, but yet needs to be digged out.

**Comment by jangsutsr** [comment]
@Fale This might be the biggest issue of 3.1.2 release, but meanwhile I suggest our current RPM builds not to be blocked by it. The cause of the test failure lies in the deficiency of our unit test tools under quite specific test environments. Both travis and our manual tests shows positive outcomes.

**Comment by Fale** [comment]
@jangsutsr Thanks :). RPMs of 3.1.1 are already on their way toward Fedora and EPEL ;) https://bodhi.fedoraproject.org/updates/?packages=python-ansible-tower-cli
