### ISSUE TITLE
inventory_script create does not accept non-ASCII characters in script

### ISSUE THREAD

**Issue by ldelouw** [ansible/tower-cli#260]
[root@tower ~]# file inventory.py 
inventory.py: Python script, UTF-8 Unicode text executable

[root@tower ~]# tower-cli inventory_script create  -n generic-dummy --organization org-generic --script "$(cat ~/inventory.py)"

Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 90, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/bin/tower-cli", line 82, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1058, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/command.py", line 43, in parse_args
    return super(Command, self).parse_args(ctx, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1390, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1675, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1359, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1349, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1338, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1336, in _convert
    return self.type(value, self, ctx)
  File "/usr/lib/python2.7/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/types.py", line 54, in convert
    if value.startswith('@'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1915: ordinal not in range(128)

In the Inventory Script to be imported, there are some non-ASCII chars like ä,ö,ß and in future some french accents as well.

Any hint for a quick fix for this issue?

Thanks

**Comment by AlanCoding** [comment]
Familiar from what was seen here:

https://github.com/ansible/tower-cli/blob/master/tower_cli/utils/parser.py#L46

A quick fix feels very probably. We'll need a test to check it across the python versions.

**Comment by ldelouw** [comment]
At line 50 in /usr/lib/python2.7/site-packages/tower_cli/utils/types.py I added:

        if isinstance(value, str):
                value = value.encode('UTF-8')
                is_unicode = True
        else:
                value = str(value)

It fails in the line  value = value.encode('UTF-8')

**Comment by jangsutsr** [comment]
@ldelouw Please try changing line `if isinstance(value, str):` into `if isinstance(value, unicode):` and see if that solves the issue. We will patch it up asap in the mean time.
