### ISSUE TITLE
unicode brokenness in 3.1.0

### ISSUE THREAD

**Issue by wenottingham** [ansible/tower-cli#269]
```
[notting@nostromo: ~]$ tower-cli job_template list
== ============================ ========= ======= ======================= 
id             name             inventory project        playbook         
== ============================ ========= ======= ======================= 
15 Apply standard configuration         5       7 apply-configuration.yml
12 Deploy application                   5       7 deploy.yml
14 Destroy cloud instances              5       7 demo-aws-delete.yml
17 fred                                 5       7 demo-aws-delete.yml
13 Provision cloud instances            5       7 demo-aws-launch.yml
== ============================ ========= ======= ======================= 
[notting@nostromo: ~]$ tower-cli job_template get 17
== ==== ========= ======= =================== 
id name inventory project      playbook       
== ==== ========= ======= =================== 
17 fred         5       7 demo-aws-delete.yml
== ==== ========= ======= =================== 
[notting@nostromo: ~]$ tower-cli job_template delete 17
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 90, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/bin/tower-cli", line 82, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/decorators.py", line 51, in answer
    return method(*inner_a, **inner_kw)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 309, in func
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 695, in delete
    url = '%s%d/' % (self.endpoint, pk)
TypeError: %d format: a number is required, not unicode
```

**Comment by jangsutsr** [comment]
This bug stays hidden in base.py since the beginning... Will bundle the solution into 3.1.1 patch.

**Comment by Fale** [comment]
is 3.1.1 going to be released soon with this or is it better if I backport this patch to the 3.1.0 rpm packages?

**Comment by jangsutsr** [comment]
@Fale We are releasing 3.1.1 today.
