### ISSUE TITLE
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by drewhemm** [ansible/tower-cli#300]
The following error occurs for me with 3.1.3 when trying to monitor a running job:

```
tower-cli job monitor 98326      
------Starting Standard Out Stream------
Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 90, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/bin/tower-cli", line 82, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tower_cli/utils/decorators.py", line 41, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tower_cli/models/base.py", line 312, in func
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tower_cli/models/base.py", line 980, in monitor
    if not content.startswith("Waiting for results"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

I found this similar issue in another project:

https://github.com/diyan/pywinrm/issues/111

I made the following change to line 980 in tower_cli/models/base.py:

Before:
```
if not content.startswith("Waiting for results"):
```

After:
```
if not content.startswith(b"Waiting for results"):
```

And the error message goes away... 

That line was introduced/modified here:

https://github.com/ansible/tower-cli/blob/1d9211b01e32768cf93dccafe2f6996d59966ada/tower_cli/models/base.py

Does the source code need fixing or is it something to do with my Python version/setup etc? I am running Python 3.5.2

**Comment by AlanCoding** [comment]
Definitely needs to be fixed on tower-cli side, as the intent is to support python 3.5, even though it is slow in coming.

I'm fine with the solution you suggest. It might also be solvable to fully coerce `content` into a str.
