### ISSUE TITLE
Problem with non-English characters coming from Tower

### ISSUE THREAD

**Issue by ribeiroh** [ansible/tower-cli#333]
Hi, 

we're trying to use tower-cli to interact with our Tower server. After configuring it, most of the options, however, throw back the following issue:

$ tower-cli job_template list
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 90, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/bin/tower-cli", line 82, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 327, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 324, in func
    output = format(result)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 445, in _format_human
    data_row += template.format(value or '') + ' '
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 19: ordinal not in range(128)

The only option we tried that did NOT give an error was 'tower-cli job list'. All the other commands we tried give similar issue.

$ echo $LANG
en_US.UTF-8

Any ideas?

Thank you!

**Comment by ribeiroh** [comment]
We found the issue. The problem was having data on Tower with non-English characters. It seems that tower-cli is not handling those characters correctly.

Please let me know if I can provide any further useful information to help fixing the problem.

**Comment by AlanCoding** [comment]
I was able to replicate this by adding "日本語" to the name of one of the job templates.

Also, if the name with unicode does not appear in the page being displayed, or if the unicode string is in `description` field (not displayed in console) then the error will not occur. So this seems squarely in processing for printing to the console in tower-cli.

**Comment by AlanCoding** [comment]
The column widths might not be correct (which is a much more difficult problem), but we have fix staged that will get this working, ready to be released in 3.1.8
