### ISSUE TITLE
issue with json file while trying to configure settings

### ISSUE THREAD

**Issue by jlozadad** [ansible/tower-cli#352]
while trying to use ` tower-cli setting modify AUTH_LDAP_ORGANIZATION_MAP @ldap_team_mapping.json -vvv`

I get the following:
`
*** DETAILS: Getting records. *************************************************
GET https://localhost:8043/api/v1/settings/all/
Params: {}

OPTIONS https://localhost:8043/api/v1/settings/all/

Traceback (most recent call last):
  File "/home/jlozadad/.local/bin/tower-cli", line 27, in <module>
    cli()
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/tower_cli/cli/base.py", line 80, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/tower_cli/conf.py", line 327, in method_with_context_managed
    method(*args, **kwargs)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/tower_cli/cli/resource.py", line 101, in func
    result = method(*args, **kwargs)
  File "/home/jlozadad/.local/lib/python2.7/site-packages/tower_cli/resources/setting.py", line 91, in modify
    data={setting: self.coerce_type(setting, value)}
  File "/home/jlozadad/.local/lib/python2.7/site-packages/tower_cli/resources/setting.py", line 119, in coerce_type
    return ast.literal_eval(value)
  File "/usr/lib64/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib64/python2.7/ast.py", line 63, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib64/python2.7/ast.py", line 62, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib64/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
`
but, if I use the same json and configure it on the UI it works fine.

Tower CLI 3.1.7
Ansible Tower 1.0.0-341-gc695234

**Comment by jlozadad** [comment]
so we were able to solve it by having all boolean values with quotes.
all boolean vaules should be quoted
example:
` 
"remote": "true"
`

**Comment by jlozadad** [comment]
Looks like the actual fix is 
`
"remote": True
`
Basically capitalize true.

**Comment by AlanCoding** [comment]
I'm not a fan of the syntax `"remote": True`, because the JSON format standard would be `"remote": true`. I can see how this might be caused by `ast.literal_eval`, but it's confusing what the original intent of this was. I agree this isn't behaving in-line with what a user should expect.

**Comment by jlozadad** [comment]
not sure if this is the same issue or bug but, here is another example:
`
tower-cli setting modify AUTH_LDAP_USER_FLAGS_BY_GROUP @user_flags.json
Error: The Tower server claims it was sent a bad request.

PATCH https://"name"/api/v1/settings/all/
Params: None
Data: {"AUTH_LDAP_USER_FLAGS_BY_GROUP": [{"is_superuser": "CN=Administrators,OU=Globe,OU=Accounts,DC=red,DC=blue,DC=red,DC=com"}]}

Response: {"AUTH_LDAP_USER_FLAGS_BY_GROUP":["Expected a dictionary of items but got type \"list\"."]}
`

**Comment by AlanCoding** [comment]
I think the `AUTH_LDAP_USER_FLAGS_BY_GROUP` is a different issue, and the response is an error from the server. If that is a problem, then it should be filed as an AWX issue.
