### ISSUE TITLE
"TypeError: Resource subclasses must have an `endpoint`." on Mac OS X Yosemite 

### ISSUE THREAD

**Issue by gengmao** [ansible/tower-cli#42]
That's what I got
```
mao-mac:sumo mao (master) $ tower-cli user list
Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 80, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 931, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Library/Python/2.7/site-packages/click/core.py", line 970, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/bin/tower-cli", line 68, in get_command
    resource = tower_cli.get_resource(name)
  File "/Library/Python/2.7/site-packages/tower_cli/__init__.py", line 32, in get_resource
    module = importlib.import_module('tower_cli.resources.%s' % name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/tower_cli/resources/user.py", line 16, in <module>
    from tower_cli import models
  File "/Library/Python/2.7/site-packages/tower_cli/models/__init__.py", line 18, in <module>
    from tower_cli.models.base import BaseResource, Resource, MonitorableResource
  File "/Library/Python/2.7/site-packages/tower_cli/models/base.py", line 125, in <module>
    class BaseResource(six.with_metaclass(ResourceMeta)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/tower_cli/models/base.py", line 112, in __new__
    raise TypeError('Resource subclasses must have an `endpoint`.')
TypeError: Resource subclasses must have an `endpoint`.
```

**Comment by gengmao** [comment]
This is a duplicate of https://github.com/ansible/tower-cli/issues/41. Problem is resolved by installing ansible-tower-cli through python 2.7.9

**Comment by starboarder2001** [comment]
I am getting the same thing with Python 2.7.10

$ tower-cli user list
Traceback (most recent call last):
  File "/opt/zenoss/libexec/tower-cli-virtualenv/bin/tower-cli", line 80, in <module>
    cli()
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/click/core.py", line 986, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/click/core.py", line 1025, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/bin/tower-cli", line 68, in get_command
    resource = tower_cli.get_resource(name)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/tower_cli/__init__.py", line 32, in get_resource
    module = importlib.import_module('tower_cli.resources.%s' % name)
  File "/opt/zenoss/libexec/bin/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/tower_cli/resources/user.py", line 16, in <module>
    from tower_cli import models
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/tower_cli/models/__init__.py", line 18, in <module>
    from tower_cli.models.base import BaseResource, Resource, MonitorableResource
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/tower_cli/models/base.py", line 125, in <module>
    class BaseResource(six.with_metaclass(ResourceMeta)):
  File "/opt/zenoss/lib/python/six.py", line 353, in with_metaclass
    return meta("NewBase", (base,), {})
  File "/opt/zenoss/libexec/tower-cli-virtualenv/lib/python2.7/site-packages/tower_cli/models/base.py", line 112, in __new__
    raise TypeError('Resource subclasses must have an `endpoint`.')
TypeError: Resource subclasses must have an `endpoint`.
