### ISSUE TITLE
Error while running monitor option on launching of workflow template

### ISSUE THREAD

**Issue by Rajnita** [ansible/tower-cli#464]
Following error occurs when I try to monitor the workflow template

rleichom$ tower-cli workflow_job launch --workflow-job-template 13 --monitor
------Starting Standard Out Stream------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.2.1', 'console_scripts', 'tower-cli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tower_cli/cli/base.py", line 81, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tower_cli/conf.py", line 358, in method_with_context_managed
    method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tower_cli/resources/workflow_job.py", line 157, in launch
    return self.monitor(workflow_job_id, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tower_cli/models/base.py", line 827, in monitor
    if not content.startswith(b"Waiting for results"):
TypeError: startswith first arg must be str or a tuple of str, not bytes

**Comment by AlanCoding** [comment]
I can't explain why this was introduced before:

https://github.com/ansible/tower-cli/commit/9bbd8aad6b6c1de4ee24bbf2dcbb1be5831ddb72

I can reproduce the described situation. In python3, you'll get this if `content` is a string. But I don't know what _other_ situation we were trying to protect against.
