### ISSUE TITLE
not able to modify groups that are created from Tower

### ISSUE THREAD

**Issue by oatakan** [ansible/tower-cli#494]
When I create a group using tower-cli, I can then modify using `tower-cli group modify`. However when I try to modify a group that is created from Tower, I get the following error:

```
tower-cli group modify 11686 --variables "test: value"
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 90, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/bin/tower-cli", line 82, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 327, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 311, in func
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/group.py", line 200, in modify
    isid = self._get_inventory_source_id(answer)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/group.py", line 316, in _get_inventory_source_id
    return int(group['related']['inventory_source'].split('/')[-2])
KeyError: 'inventory_source'
```

This is due to the fact that **related.inventory_source** field is not added from Tower but it gets added by tower-cli. When I get the group details with tower-cli,  it's missing the field **related.inventory_source**. This issue also impacts the [tower_group](http://docs.ansible.com/ansible/latest/tower_group_module.html) module as it uses the tower-cli library.

`tower-cli group list -n 'top-group' -i 'demo-update-group' -f yaml
count: 1
next: null
previous: null
results:
- id: 11686
  type: group
  url: /api/v1/groups/11686/
  related:
    created_by: /api/v1/users/3/
    modified_by: /api/v1/users/1/
    job_host_summaries: /api/v1/groups/11686/job_host_summaries/
    variable_data: /api/v1/groups/11686/variable_data/
    job_events: /api/v1/groups/11686/job_events/
    potential_children: /api/v1/groups/11686/potential_children/
    ad_hoc_commands: /api/v1/groups/11686/ad_hoc_commands/
    all_hosts: /api/v1/groups/11686/all_hosts/
    activity_stream: /api/v1/groups/11686/activity_stream/
    hosts: /api/v1/groups/11686/hosts/
    children: /api/v1/groups/11686/children/
    inventory_sources: /api/v1/groups/11686/inventory_sources/
    inventory: /api/v1/inventories/27/
  summary_fields:
    inventory:
      id: 27
      name: demo-update-group
      description: ''
      has_active_failures: false
      total_hosts: 0
      hosts_with_active_failures: 0
      total_groups: 4
      groups_with_active_failures: 0
      has_inventory_sources: false
      total_inventory_sources: 0
      inventory_sources_with_failures: 0
      organization_id: 2
      kind: ''
    created_by:
`

**Comment by AlanCoding** [comment]
What version of tower-cli and Tower are you using?

**Comment by oatakan** [comment]
I tried with 3.2.2 and 3.2.3 and the same results on both.

**Comment by AlanCoding** [comment]
the line number

```
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/group.py", line 200, in modify
```

looks like it corresponds to a version _of tower-cli_ before 3.2

**Comment by oatakan** [comment]
that's what  suspect Tower 3.2 implementation changed how groups are created from Tower. Specifically, decoupling groups from inventory source which seems to be the cause for this compatibility issue.
