### ISSUE TITLE
Running `tower-cli label create` with a job template specified multiple times fails with stacktrace.

### ISSUE THREAD

**Issue by poiriermike** [ansible/tower-cli#499]
## 
tower-cli version 3.2.1
python version 3.5.2

## Expected result

Error message, or no-op.

## Actual result 

```
Traceback (most recent call last):
  File "HOME/.local/share/virtualenvs/ansible/bin/tower-cli", line 11, in <module>
    sys.exit(cli())
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/tower_cli/cli/base.py", line 81, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/tower_cli/conf.py", line 358, in method_with_context_managed
    method(*args, **kwargs)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "HOME/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/tower_cli/resources/label.py", line 88, in create
```

## Steps to reproduce
1. Run `tower-cli label create --name <label> --organization <org> --job-template <template>`
1. Run the same command again: `tower-cli label create --name <label> --organization <org> --job-template <template>`

Looks like its passing an incorrect number of args to the associate_label function in job_template.

**Comment by AlanCoding** [comment]
Thanks for the report!
