### ISSUE TITLE
[AWX refile] Problem with non ASCII characters in awx-cli receive

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#562]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When I use `awx-cli receive` to migrate data, I have unicode characters in the content files. During the import I have an error.

##### ENVIRONMENT
* AWX version: 1.0.2 -> 1.0.6 (target)
* AWX install method: docker on linux
* Ansible version:  2.4.2 -> 2.5.5 (target)
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1 - Import data in file with `awx-cli receive -u admin  -p ***** -h http://ansible-build --all > assets.json`
2 - an extract from the file :  
```
  {
    "inputs": {
      "vault_password": ""
    },
    "name": "Ingdev Forge Vault Master",
    "asset_type": "credential",
    "credential_type": "Vault",
    "organization": "Ing\u00e9nieries de d\u00e9veloppement",
    "asset_relation": {
      "roles": [
        {
          "team": [],
          "name": "Use",
          "user": []
        },
        {
          "team": [],
          "name": "Read",
          "user": []
        },
        {
          "team": [
            "Ing\u00e9nieries de d\u00e9veloppement - Forge"
          ],
          "name": "Admin",
          "user": [
            "97000t"
          ]
        }
      ]
    }
```
3 - export the data to the target server : `awx-cli send -u admin  -p ***** -h http://ansible-target assets.json`

##### EXPECTED RESULTS

Data has been migrated with special characters like "é"

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/bin/awx-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'awx-cli')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 51, in send
    self.print_header_row(asset_type, asset_name)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/logging_command.py", line 27, in print_header_row
    self.my_print("{} [{}] {}".format(asset_type.replace("_", " ").upper(), asset_name, stars))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 4: ordinal not in range(128)
```

##### ADDITIONAL INFORMATION

Issue copied from https://github.com/ansible/awx/issues/2029

**Comment by icsm2017** [comment]
Any update since 28 jun ?

**Comment by icsm2017** [comment]
Since I tried to translate the characters with corresponding letters. No errors. 
But when I try to migrate it seems that invisible characters affect the file.

**Comment by krent84** [comment]
I have the same problem. when will the fix be released?

**Comment by alxndr13** [comment]
@AlanCoding thanks for your effort. Is there any update to this issue?

**Comment by AlanCoding** [comment]
Looks like this may have been fixed in https://github.com/ansible/tower-cli/pull/613. Is anyone still seeing the error with recent releases? If you are, could you provide the traceback?

**Comment by jainnikhil30** [comment]
@AlanCoding 

I am still seeing an error with non-ascii character with latest tower-cli (3.3.3)

```

Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 370, in send
    sender.send(source, prevent, exclude, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 218, in send
    self.log_change("Created {} {}".format(asset_type, asset_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11: ordinal not in range(128)
```

**Comment by AlanCoding** [comment]
Thanks, this is a new bug

https://github.com/ansible/tower-cli/blob/287fc9ad6ba333b215d1b679eaac6c0b40c120af/tower_cli/cli/transfer/send.py#L218

Could be even more places to fix

https://github.com/ansible/tower-cli/blob/287fc9ad6ba333b215d1b679eaac6c0b40c120af/tower_cli/cli/transfer/send.py#L220

https://github.com/ansible/tower-cli/blob/fffcbd2fb0551b711b86fea7705ad67a72ff6ebd/tower_cli/cli/transfer/logging_command.py#L88

**Comment by sdmorel** [comment]
Can confirm this is still present on 3.3.4

**Comment by Ovski4** [comment]
Still present on 3.3.8
