### ISSUE TITLE
API: Host - associate: Only primary keys but no names work

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/tower-cli#575]
According to the API-specification, the host and group variables of associate accept either IDs or their names.

When using names I get the following error:
```
>>>host_resource.associate(name="foobar12", group="gatewayed")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/models/fields.py", line 198, in method
    return internal_method(method._relationship, obj_pk, other_obj_pk)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/models/base.py", line 556, in _assoc
    url = self.endpoint + '%d/%s/' % (me, url_fragment)
TypeError: %d format: a number is required, not NoneType
```

but when using their IDs, everything works fine:
```
>>> host_resource.associate(host=94, group=1)
{'changed': True}
```

More interesting is, that the CLI accepts names:
```
 tower-cli host associate --host=foobar12 --group=gatewayed
OK. (changed: false)
```

**Comment by AlanCoding** [comment]
Yes, this is an architectural shortcoming.

We use the click library to decorate these methods, and the click type constructs to do pre-processing of the input CLI flags. That means that the interface for the actual function call is post-processing of those types.

I do want to attempt a redesign of this, although for a different reason. With the types system we have, we can only lookup with that one particular input, but I would like to use common fields between different input arguments to assist in the lookup (in this case, share an `--inventory` parameter between the host & group lookup). But given that this should be shifting the lookup to internal to the method, it's probable that it would enable the use case you mention as well.
