### ISSUE TITLE
.tower_cli.cfg  throws a stacktrace with a % in the password field

### ISSUE THREAD

**Issue by poiriermike** [ansible/tower-cli#576]
## Symptom
With a .tower_cli.cfg file like such:
```
[general]
username = ansibleuser
password = changme%blah
host = https://ansible.tower.com
```
tower-cli fails to parse the config file.

## Expected Behaviour
Tower uses the password successfully

## Actual Behaviour
Stacktrace
```
Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 9, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'tower-cli')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/models/base.py", line 529, in list
    response = self.read(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/models/base.py", line 288, in read
    r = client.get(url, params=kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/api.py", line 217, in request
    settings.password,
  File "/usr/local/lib/python3.4/dist-packages/tower_cli/conf.py", line 217, in __getattr__
    value = parser.get('general', key)
  File "/usr/lib/python3.4/configparser.py", line 773, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 374, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 423, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%blah'"

```

**Comment by srgvg** [comment]
Can confirm this happens.
