### ISSUE TITLE
Creating a Schedule with 'create_on_missing=True' doesn't seem to work

### ISSUE THREAD

**Issue by dmsimard** [ansible/tower-cli#578]
I'm currently developing a module for managing Tower schedules and I'd like to use the same approach as ``tower_project`` which ensures the state of the resource by doing a ``modify`` with ``create_on_missing=True``: https://github.com/ansible/ansible/blob/1199dff24638736a2401967eff9c37d5da07223b/lib/ansible/modules/web_infrastructure/ansible_tower/tower_project.py#L143-L164

However, I'm getting the following trace when attempting to do that:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6rGrUn/ansible_module_tower_schedule.py", line 246, in <module>
    main()
  File "/tmp/ansible_6rGrUn/ansible_module_tower_schedule.py", line 235, in main
    result = schedule.modify(**params)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/schedule.py", line 84, in decorator_with_pk
    result = func(obj, pk=pk, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 698, in modify
    return self.write(pk, create_on_missing=create_on_missing, force_on_exists=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 411, in write
    r = getattr(client, method.lower())(url, data=kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/api.py", line 276, in request
    "%s method to that URL (%s)." % (method, url),
tower_cli.exceptions.MethodNotAllowed: The Tower server says you can't make a request with the POST method to that URL (http://localhost/api/v2/schedules/).
```

The modify works if the Schedule already exists.

Is it because a schedule is a related object ?

**Comment by dmsimard** [comment]
If you'd like to test the actual module, I've opened up a PR here: https://github.com/ansible/ansible/pull/43437

**Comment by AlanCoding** [comment]
I understand on the server-side what this error is saying:

> tower_cli.exceptions.MethodNotAllowed: The Tower server says you can't make a request with the POST method to that URL (http://localhost/api/v2/schedules/).

The server doesn't allow creating a schedule via the schedules list, it forces the client to do it via a sublist. For example:

```
tower-cli schedule create --enabled=false --job-template=1009 --rrule="DTSTART:20180718T155801Z RRULE:FREQ=MONTHLY;INTERVAL=1" --name="foo jt schedule" -v
*** DETAILS: Checking for an existing record. *********************************
GET http://localhost:8013/api/v2/job_templates/1009/schedules/
Params: [('name', u'foo jt schedule'), ('unified_job_template', 1009)]

*** DETAILS: Writing the record. **********************************************
POST http://localhost:8013/api/v2/job_templates/1009/schedules/
Data: {'enabled': False, 'unified_job_template': 1009, 'rrule': u'DTSTART:20180718T155801Z RRULE:FREQ=MONTHLY;INTERVAL=1', 'name': u'foo jt schedule'}

Resource changed.
== =============== ==================== ======= 
id      name       unified_job_template enabled 
== =============== ==================== ======= 
49 foo jt schedule                 1009   false
== =============== ==================== ======= 
```

So the tower-cli methods for schedule creation go through some extra steps in order to hit the endpoint `http://localhost:8013/api/v2/job_templates/1009/schedules/` instead of `http://localhost:8013/api/v2/schedules/`, which you can't use.
