### ISSUE TITLE
workflow associate_label doesn't work in v3.3.0

### ISSUE THREAD

**Issue by sumkincpp** [ansible/tower-cli#589]
Used software versions are
```
Tower CLI 3.3.0
API v2
AWX 1.0.6.8
Ansible 2.5.3
```

Associating label results on undefined type for  `workflow_job_template` :
```bash
# tower-cli workflow associate_label
Usage: tower-cli workflow associate_label [OPTIONS]

  Associate a label with this workflow_job_template.

Local Options:
  --workflow_job_template WORKFLOW_JOB_TEMPLATE
                                  [required]
  --label LABEL                   [required]

Global Options:
  --use-token                     Turn on Tower's token-based authentication.
                                  No longer supported in Tower 3.3 and above.
  --certificate TEXT              Path to a custom certificate file that will
                                  be used throughout the command. Overwritten
                                  by --insecure flag if set.
  --insecure                      Turn off insecure connection warnings. Set
                                  config verify_ssl to make this permanent.
  --description-on                Show description in human-formatted output.
  -v, --verbose                   Show information about requests being made.
  -f, --format [human|json|yaml|id]
                                  Output format. The "human" format is
                                  intended for humans reading output on the
                                  CLI; the "json" and "yaml" formats provide
                                  more data, and "id" echos the object id
                                  only.
  -p, --tower-password TEXT       Password to use to authenticate to Ansible
                                  Tower. This will take precedence over a
                                  password provided to `tower config`, if any.
  -u, --tower-username TEXT       Username to use to authenticate to Ansible
                                  Tower. This will take precedence over a
                                  username provided to `tower config`, if any.
  -t, --tower-oauth-token TEXT    OAuth2 token to use to authenticate to
                                  Ansible Tower. This will take precedence
                                  over a token provided to `tower config`, if
                                  any.
  -h, --tower-host TEXT           The location of the Ansible Tower host.
                                  HTTPS is assumed as the protocol unless
                                  "http://" is explicitly provided. This will
                                  take precedence over a host provided to
                                  `tower config`, if any.

Other Options:
  --help  Show this message and exit.

# tower-cli workflow associate_label --workflow_job_template test --label test
Traceback (most recent call last):
  File "/opt/awx/venv/bin/tower-cli", line 11, in <module>
    sys.exit(cli())
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/awx/venv/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/opt/awx/venv/lib/python2.7/site-packages/tower_cli/cli/action.py", line 46, in parse_args
    return super(ActionSubcommand, self).parse_args(ctx, args)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/opt/awx/venv/lib/python2.7/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/opt/awx/venv/lib/python2.7/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/opt/awx/venv/lib/python2.7/site-packages/tower_cli/cli/types.py", line 128, in convert
    resource = tower_cli.get_resource(self.resource_name)
  File "/opt/awx/venv/lib/python2.7/site-packages/tower_cli/__init__.py", line 32, in get_resource
    module = importlib.import_module('tower_cli.resources.%s' % name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named workflow_job_template
```

**Comment by AlanCoding** [comment]
planning fix for release 3.3.1
