### ISSUE TITLE
Import/Export issue with umlauts in notification template

### ISSUE THREAD

**Issue by PaulRitzkat** [ansible/tower-cli#596]
### Versions
tower-cli --version: Tower CLI 3.3.0
awx version: 1.0.7

### Error
Importing notification template with umlauts in name field throws UnicodeEncodeError (i didn't test other fields with umlauts):
```
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 9, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'tower-cli')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 51, in send
    self.print_header_row(asset_type, asset_name)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/logging_command.py", line 27, in print_header_row
    self.my_print("{} [{}] {}".format(asset_type.replace("_", " ").upper(), asset_name, stars))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)
```
json file from tower-cli export (names changed to protect the innocent ;) ) the name had ü in it's name:
```json
[
  {
    "notification_type": "email",
    "organization": "Default",
    "notification_configuration": {
      "username": "",
      "sender": "awx@email",
      "recipients": [
        "user@email"
      ],
      "use_tls": false,
      "host": "smtp.server",
      "use_ssl": false,
      "password": "",
      "port": 25
    },
    "asset_type": "notification_template",
    "name": "User Uml\u00fcaut"
  }
]

```

**Comment by AlanCoding** [comment]
https://github.com/ansible/tower-cli/blob/2c115877a36238b94fb8af1ff32915ebaf868e60/tower_cli/cli/transfer/logging_command.py#L27

This can probably be solved `"{} [{}] {}"` -> `six.text_type("{} [{}] {}")`

**Comment by PaulRitzkat** [comment]
tower-cli --version: Tower CLI 3.3.0
awx: 2.0.1
asset.json export from awx 1.0.7.2

```
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 9, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'tower-cli')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 51, in send
    self.print_header_row(asset_type, asset_name)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/logging_command.py", line 27, in print_header_row
    self.my_print("{} [{}] {}".format(asset_type.replace("_", " ").upper(), asset_name, stars))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)
```
The offending line is probably again the last name of a colleague and the ü (\u00fc).
