### ISSUE TITLE
ImportError: cannot import name UnrewindableBodyError

### ISSUE THREAD

**Issue by flynn1973** [ansible/tower-cli#603]
````
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'tower-cli')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/run.py", line 17, in <module>
    from tower_cli.cli.base import TowerCLI
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 25, in <module>
    from tower_cli.cli import misc
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 24, in <module>
    from requests.auth import HTTPBasicAuth
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 4, in <module>
    from .request import make_headers
  File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError

````

**Comment by jainnikhil30** [comment]
@flynn1973  This seems to be an issue with requests rather than tower-cli. Can you please try following steps to re-install requests and urlib3 to see if it helps ?

```
# sudo pip uninstall requests
# sudo pip uninstall urllib3
# sudo yum remove python-urllib3
# sudo yum remove python-requests
```
Confirm all the above libraries have been removed by executing the below command:
```
# rpm -qa | grep requests 
# pip freeze | grep requests
```
Now, install those packages using yum:
```
# sudo yum install python-urllib3
# sudo yum install python-requests
```

**Comment by MatheMatrix** [comment]
> @flynn1973 This seems to be an issue with requests rather than tower-cli. Can you please try following steps to re-install requests and urlib3 to see if it helps ?
> 
> ```
> # sudo pip uninstall requests
> # sudo pip uninstall urllib3
> # sudo yum remove python-urllib3
> # sudo yum remove python-requests
> ```
> 
> Confirm all the above libraries have been removed by executing the below command:
> 
> ```
> # rpm -qa | grep requests 
> # pip freeze | grep requests
> ```
> 
> Now, install those packages using yum:
> 
> ```
> # sudo yum install python-urllib3
> # sudo yum install python-requests
> ```

it works! really thanks :-D

**Comment by 123BLiN** [comment]
In my case I also would need to reinstall awscli itself with:
`pip install --upgrade --user awscli` after reinstalling requests and urllib

**Comment by flynn1973** [comment]
ok this seems to be fixed, closing.

**Comment by FaizullahKhan** [comment]
this method of uninstalling and installing of requests module through pip and yum is resolving other issues as well related to  {"changed": false, "msg": "Failed to import docker or docker-py - No module named requests.exceptions. Try `pip install docker` or `pip install docker-py`

**Comment by Santoshk53** [comment]
> @flynn1973 This seems to be an issue with requests rather than tower-cli. Can you please try following steps to re-install requests and urlib3 to see if it helps ?
> 
> ```
> # sudo pip uninstall requests
> # sudo pip uninstall urllib3
> # sudo yum remove python-urllib3
> # sudo yum remove python-requests
> ```
> 
> Confirm all the above libraries have been removed by executing the below command:
> 
> ```
> # rpm -qa | grep requests 
> # pip freeze | grep requests
> ```
> 
> Now, install those packages using yum:
> 
> ```
> # sudo yum install python-urllib3
> # sudo yum install python-requests
> ```

Really thanks for this!

**Comment by cybergavin** [comment]
I was using Ansible and after installing Azure CLI with Python3, this issue occurred. The above solution worked for me too. Thank you.
