### ISSUE TITLE
[Docs] What is correct extra_vars format or Job Template create/modify operations?

### ISSUE THREAD

**Issue by lorddaedra** [ansible/tower-cli#624]
Hello) 

Please, provide example how to create Job Template via tower_cli (inside Python script), with extra_vars, I've got error 

> tower_cli.exceptions.TowerCLIError: failed to parse some of the extra variables.

My code is:
```
job_template_config = {
    'extra_vars': yaml.safe_dump(some_dict_with_my_extra_vars),
    ...
}
get_resource('job_template').create(**job_template_config)
```

Doc page: https://tower-cli.readthedocs.io/en/latest/api_ref/resources/job_template.html

**Comment by lorddaedra** [comment]
```
Traceback (most recent call last):
...
    new_job_template = job_template_res.create(**job_template_config)
  File "/usr/local/lib/python3.7/site-packages/tower_cli/models/base.py", line 618, in create
    return self.write(create_on_missing=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tower_cli/resources/job_template.py", line 124, in write
    return super(Resource, self).write(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tower_cli/models/base.py", line 1137, in write
    kwargs['extra_vars'] = parser.process_extra_vars(kwargs['extra_vars'])
  File "/usr/local/lib/python3.7/site-packages/tower_cli/utils/parser.py", line 130, in process_extra_vars
    opt_dict = string_to_dict(extra_vars_opt, allow_kv=True)
  File "/usr/local/lib/python3.7/site-packages/tower_cli/utils/parser.py", line 105, in string_to_dict
    'variables.\nvariables: \n%s' % var_string
tower_cli.exceptions.TowerCLIError: failed to parse some of the extra variables.
variables:
{
```

**Comment by lorddaedra** [comment]
Looks like need use list of yaml strings for each of extra_vars instead of yaml for all extra_vars.

So something like:


```python3
extra_vars = [
    yaml.safe_dump({'var1': 'value1'}), 
    yaml.safe_dump({'var2': 'value2'}), 
    yaml.safe_dump({'var3': 'value3'}), 
    yaml.safe_dump({'var4': 'value4'}),
]
```

**Comment by p1rateg0ld** [comment]
Thats pretty silly. Took me awhile to figure this out. Works with json.dumps as well
