### ISSUE TITLE
unicode issues when importing assets

### ISSUE THREAD

**Issue by axlroden** [ansible/tower-cli#626]
I have an asset described as so in the json (this was exported with tower-cli):

```javascript
        {
          "name": "M\u00fdvatn", 
          "sub_groups": [], 
          "variables": "{}", 
          "hosts": [
            "thor_4528"
          ], 
          "description": "imported"
        }, 
```

FYI its an Icelandic name/town (not sure :)), Mývatn.

```
tower-cli send 
crashes at that with this:

Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 284, in send
    self.import_inventory_groups(existing_object, relations[a_relation])
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 1071, in import_inventory_groups
    self.import_sub_groups(groups, existing_groups, existing_name_to_id, existing_object, None)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 1105, in import_sub_groups
    self.add_group(inventory=inventory, parent=parent_project, group=group)
  File "/usr/local/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 1192, in add_group
    self.log_change("Added group {}".format(group['name']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 18: ordinal not in range(128)
```

**Comment by AlanCoding** [comment]
This should be easy to fix, universally, we should use the pattern of `six.text_type("Added group {}.").format(group['name'])`
