### ISSUE TITLE
tower-cli fails to import dump with custom credential type

### ISSUE THREAD

**Issue by UnixArena** [ansible/tower-cli#641]
Unable to send the information to the target node. 

From the Primary server,
`# tower-cli receive --all > AWX_Primary.06122018`

On replica node,
```
root@UnixArena~# tower-cli send  AWX_Primary.06122018
USER [admin] *************************************************************************************************************************
 [WARNING]: BUG, unknown keys for option username found in asset type of user:
{
    "type": "string",
    "required": true,
    "label": "Username",
    "help_text": "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
    "max_length": 150,
    "filterable": true

Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/transfer/send.py", line 108, in send
    self.set_password_in_custom_credential(an_asset, asset_name)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/transfer/send.py", line 1498, in set_password_in_custom_credential
    if field['id'] in credential_type_object['inputs']['required']:
KeyError: 'required'
```

**Comment by Lingeswaran-R** [comment]
As a workaround, I have deleted the custom credentials. Then, 

Export on the primary node.
`# tower-cli receive --all`

Import on the second node.
`# tower-cli send AWX_Primary.06122018`

![image](https://user-images.githubusercontent.com/14263507/49582675-cc60f500-f97b-11e8-9885-91b93a2b8d83.png)


Lingesh
[(https://www.UnixArena.com)]
