### ISSUE TITLE
"tower-cli send" failed when label already existed

### ISSUE THREAD

**Issue by mtd00001** [ansible/tower-cli#663]
- Tower CLI 3.3.2
- AWX 3.0.0.0
- Ansible 2.7.6

```
tower-cli receive --all --format json | jq ' .[] | select(.asset_type == "workflow") ' | jq -s '.' > workflow.json
tower-cli send workflow.json
```

If there is a label listed in workflow.json, but this same label (ie. with the same name) has already previously been created inside AWX prior to the execution of the "tower-cli send" command, the following error would occur and the "send" command would stop.

```

*** DETAILS: Checking for an existing record. *********************************
GET http://<awx_url>/api/v2/labels/
Params: [('name', 'A LABEL')]

*** DECISION: Record already exists, and --force-on-exists is off; do nothing. 

Added label A LABEL
Traceback (most recent call last):
  File "/bin/tower-cli", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 370, in send
    sender.send(source, prevent, exclude, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 294, in send
    self.import_labels(existing_object, relations[a_relation], asset_type)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 1014, in import_labels
    'label': created_label['id'],
  File "/usr/lib/python2.7/site-packages/tower_cli/models/fields.py", line 198, in method
    return internal_method(method._relationship, obj_pk, other_obj_pk)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 576, in _assoc
    url = self.endpoint + '%d/%s/' % (me, url_fragment)
TypeError: %d format: a number is required, not NoneType
```

There is currently no "--force-on-exists" option available for "tower-cli send" command, so I am not sure how to overcome this.

Thanks

**Comment by mtd00001** [comment]
Any assistance on this?
