### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by FedericoOlivieri** [ansible/tower-cli#696]
tower-cli version: **Tower CLI 3.3.0**
command: `tower-cli job launch --job-template=SPaC_dev --monitor`

```
Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'tower-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/resources/job.py", line 248, in launch
    return self.monitor(job_id, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/tower_cli/models/base.py", line 840, in monitor
    if not six.text_type(content).startswith("Waiting for results"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 1: ordinal not in range(128)
```

**Comment by FedericoOlivieri** [comment]
Upgrade to version 3.3.3 seems to fix the issue
